import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ToasterProvider from "./providers/ToasterProvider";
import SIgnalRProvider from "./providers/SIgnalRProvider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Carsties",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body>
    //     <SessionProvider>
    //       <ToasterProvider />
    //       <NavBar />
    //       <main className="container mx-auto px-5 pt-10">
    //         {/* All children can now rely on the SignalR connection being active */}
    //         <SIgnalRProvider>{children}</SIgnalRProvider>
    //       </main>
    //     </SessionProvider>
    //   </body>
    // </html>
    <html lang="en">
      <body>
        <SessionProvider>
          <ToasterProvider />
          <NavBar />
          <main className="container mx-auto px-5 pt-10">
            {/* All children can now rely on the SignalR connection being active */}
            <SIgnalRProvider>{children}</SIgnalRProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
